### ISSUE TITLE
Missing columns in complete Repository dataset for items 450 - 492

### ISSUE THREAD

**Issue by OliviaKirtley** [ykkunkels/ESIR_portal#20]
When downloading the full set of items from the Repository, items 450 - 492 (Schneider - University of Geneva) have missing data in the following columns:

- description
- comment
- response_scale_discrete
- response_scale_vas
- branched_from
- branched_response
- beep_level
- beeps_per_day
- morning
- evening	event
- other
- children
- adolescents
- adults
- elderly
- gen_pop
- outpatient
- inpatient
- which
- dataset

The issue originally occurred because the relevant columns were hidden in the completed item submission template for these items.

In Summer 2022, I updated the item submission template for these items (on OSF). I just checked again and in the file on the OSF, these columns are visible and data are present for the following columns:

- Item description
- Additional comments
- Response scale discrete
- Response scale VAS
- Branched from
- Required response for branching
- Beep level
- Beeps per day
- Morning questionnaire
- Evening questionnaire
- Event-contingent
- Other (please describe)
- Children
- Adolescents
- Adults
- Older adults/elderly
- General population
- Clinical sample - outpatient
- Clinical sample - inpatients
- Clinical sample - which
- Dataset

Note: These items were submitted with the first version of the item submission template, so column order differs from current order in Repository and current template.

**Comment by BenjaminKunc** [comment]
Do we have an older version of this dataset? I checked the file in the Repository (Uploaded to the Repository folder) and these columns are missing: Remarks, Which datasets does this item appear in, Contact person for each dataset + Email.

If the columns were there in some previous versions, then it would be best to add the columns back into the file. If the items were submitted like this, then I suppose it would be best to contact the researchers if they would be willing to provide these missing information. Another option would be to create empty columns with the same names (this is necessary for executing Laura's script on formatting the dataset into older template structure) and keep them empty for now.

**Comment by OliviaKirtley** [comment]
Hi Ben, Have you checked the relevant submission file on the OSF to ensure these columns are visible there (I checked before, but probably worth someone else checking). I don't think those columns have ever been visible in the main Repository dataset, so my sense is that fixing this will involve adding the missing columns from the individual submission .csv into the main Repository dataset again.

**Comment by BenjaminKunc** [comment]
I might have overlooked something but it seems to me that the original submission file does not include these columns. That is, not only that the information are missing, but it seems that these columns have been deleted from the particular submission template at some point. 

The columns _dataset_ and _contact_ are both in the main Repository file and the new submission template (which was used in this case), just under different names. However, the submission template with the items from Schneider has neither of these columns. I also tried unhiding columns in Excel and they still seem to be missing. 

I checked both the current and older version of this dataset, yet I couldn't find these columns.

**Comment by ykkunkels** [comment]
Hi Ben and Olivia,

All versions of the data can be found on OSF (https://osf.io/5ba2c). You can click on the counterclockwise arrow at the right-side of the screen to see all 23 versions.

I just scanned it quickly, and in the newer versions (from version 20 onward) there is no _"Remarks"_ column, but in older versions (version 19 and before) there is. At this point the format of the data was revised, droping columns and adjusting column-names.

**Comment by BenjaminKunc** [comment]
Hi Yoram,

I checked the submitted items once again and I found out that I indeed overlooked the columns including information on dataset name and contact info.

I added the missing information into the main Repository file and uploaded it as a new version to OSF.
