### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by BenjaminKunc** [ykkunkels/ESIR_portal#35]
Some of the items in the Repository have no IDs. 

Specifically, it regards all items from the following datasets:

- "LGBTQ+ESM" and "LGBTQ + ESM"
- "DESPAI" (but not "despai")
- "Parent Experience"
- " MEDAL  and ESM_EXRUMEM_Schmitter23"
- "ESM_EXRUMEM_Schmitter23"
- "GRIEF IN DAILY LIFE PART 1 + GRIEF IN DAILY LIFE PART 2"

Since the IDs are hardcoded in the server.R script on line 30: " df[, "item_ID"] <- 1:nrow(df) #fill the item_ID column", it would be good to find out why the IDs are missing in these datasets.

**Comment by BenjaminKunc** [comment]
Now the IDs are added during the submission process, and are no longer missing. 

I wonder if it is necessary to keep the "df[, "item_ID"] <- 1:nrow(df)" code in the server script, since right now it seems to just rewrite the IDs every time the main file is accessed.

**Comment by ykkunkels** [comment]
Good that the submissio process now adds the ID's.

For now, we can keep the "df[, "item_ID"] <- 1:nrow(df)" code in the server script. It doesn't yet interfere and could catch manual errors.
