### ISSUE TITLE
Server disconnection issue on ESM Item Repository portal

### ISSUE THREAD

**Issue by OliviaKirtley** [ykkunkels/ESIR_portal#52]
Hi All,

I received the below message from a Repository user. I also just tested the portal and had the same issue. Please can you look into it?

Thanks,

Olivia

Subject: Website down?

Message: Hello,

I was hoping to search through the esm item repository to look for some items I can use in my next study. However, the website keeps losing connection to the server (it says "disconnected from the server - reload" in the bottom left corner). I have already tried using several different computers, but I cannot seem to get it to work. Is this a general issue? Or is there something else I should try in order to get access to the repository?

Thanks in advance!

Best,
Franziska

**Comment by ykkunkels** [comment]
Hi Olivia,

I've checked on two computers, but here the website appears to be working
fine?

Did you also experience this issue yourself? And would it be possible to
get some additional information from the person who reported it, like if
they run Windows or Mac, if they are connecting from a protected network,
etc.?

Best!
Yoram.

Op wo 20 nov 2024 om 10:16 schreef OliviaKirtley ***@***.***>:

**Comment by SteffieKUL** [comment]
Hi Yoram and Olivia,

I'm experiencing the same issue (Windows - HP Z book, protected network).

Bw,

Steffie

[cid:3400ce10-231b-4f48-b1b3-25d35cdb7c9a]



Research Coordinator

Center for Contextual Psychiatry | KU Leuven                        
ON V Herestraat 49 - bus 1029, 3000 Leuven

Tel: +3216/32 14 52
Web: www.ccp-leuven.be<http://www.ccp-leuven.be/> | CCP X: @ccp_leuven<https://twitter.com/ccp_leuven>


SAA X: @SAA2025Leuven

Web: https://www.saa2025.com/



[cid:017156d2-a9c0-4acc-9e2b-cc62e44de031]<http://www.saa2025.com>

________________________________

**Comment by OliviaKirtley** [comment]
Hi Yoram,

That's strange. I tried it myself yesterday morning and had the same issue. When I clicked on the search field, it instantly disconnected. I didn't try it again after that though.

I'll forward you the person's email and maybe you can reach out to them?

Bw

Olivia

________________________________

**Comment by BenjaminKunc** [comment]
Hi all,

I am also having the same issue. The ESMIR disconnects about 3-4 seconds after I open the website.

I tried to open it with Chrome and Edge on Windows while in the CCP office, which I suppose has a protected network.

Best wishes,
Ben

________________________________

**Comment by BenjaminKunc** [comment]
Hi all,

I wonder if the issue might be linked to the Google Drive folder in OSF. It seems that OSF cannot access it (see screenshot), and I think it is where citations are stored, right? It could also be something entirely different, but we will probably need to solve this anyway.

[cid:e5f6d944-a617-45dd-96ab-abf295116721]

Best wishes,
Ben

________________________________

**Comment by OliviaKirtley** [comment]
Hi All,

Thanks for looking into this. I put out messages on Bluesky and X to let people know there is an issue and we’re aware of it. Let me know when things are sorted and I will put out another message to say things have been solved.

Bw

Olivia

Professor Olivia Kirtley
Assistant Research Professor
Center for Contextual Psychiatry
KU Leuven
Onderzoeksgroep Psychiatrie
ON V Herestraat 49 - bus 1029
3000 Leuven

Tel: +3216320604
Web: www.ccp-leuven.be<about:blankwww.ccp-leuven.be>
CCP Twitter: @ccp_leuven<https://twitter.com/ccp_leuven>
Personal Twitter: @LivveyKirtley<https://twitter.com/livveykirtley>
Open Science Framework profile: osf.io/xt6mf<https://osf.io/xt6mf/>



From: BenjaminKunc ***@***.***>
Reply to: ykkunkels/ESIR_portal ***@***.***>
Date: Thursday, 21 November 2024 at 11:18
To: ykkunkels/ESIR_portal ***@***.***>
Cc: Olivia Kirtley ***@***.***>, Author ***@***.***>
Subject: Re: [ykkunkels/ESIR_portal] Server disconnection issue on ESM Item Repository portal (Issue #52)

Hi all,

I wonder if the issue might be linked to the Google Drive folder in OSF. It seems that OSF cannot access it (see screenshot), and I think it is where citations are stored, right? It could also be something entirely different, but we will probably need to solve this anyway.

[cid:e5f6d944-a617-45dd-96ab-abf295116721]

Best wishes,
Ben

________________________________

**Comment by ykkunkels** [comment]
OSF data call failed due to changed address (from: https://osf.io/nj92h/download to: https://osf.io/5ba2c/download).

SOLVED by fixing address in [v1.1.21; Fixed OSF data call](https://github.com/ykkunkels/ESIR_portal/commit/4771c72651ca90e0f8b387839ec46a3467cf82cb).
